pipelines:
  elastic-curator:
    group: webops
    label_template: "${COUNT}"
    materials:
      webops.importers-git:
        git: https://github.com:ukparliament/elastic-curator.git
        branch: master
        auto_update: true
    stages:
      - deploy:
          clean_workspace: true
          jobs:
            deploy:
              tasks:
                - exec:
                    command: make
                    arguments:
                      - deploy


environments:
  Web.DEVCI:
    pipelines:
      - elastic-curator
